# language=chs
font='LXGW Wenkai Screen'
show_windowed=yes
show_fullscreen=yes

hide_timeout=4000
fade_duration=300
min_mouse_move=0
bottom_hover=yes

scale_windowed=1.5
scale_fullscreen=1.5
scale_forced_window=1.5

raise_subtitles=yes

compact_mode=yes

jump_amount=10

info_button=yes

# osc_color=06020d0.067/0.067/0.067/1
