# 纵向候选列表
Vertical Candidate List=False
# 使用鼠标滚轮浏览上一页或下一页
WheelForPaging=True
# Font
Font="JetBrains Maple Mono 12"
# Menu Font
MenuFont="JetBrains Maple Mono 12"
# Tray Font
TrayFont="JetBrains Maple Mono 12"
# 偏好文本图标
PreferTextIcon=False
# 在图标中显示布局名称
ShowLayoutNameInIcon=True
# 使用输入法语言显示文本
UseInputMethodLanguageToDisplayText=True
# Theme
Theme=mint-green-dark
# Dark Theme
DarkTheme=mint-green-dark
# 如果主题和桌面支持，则遵循系统强调色
UseAccentColor=True
# 在 Wayland 下启用分数缩放
EnableFractionalScale=True
