#!/usr/sbin/nft -f

flush ruleset

define TPROXY_MARK=0xff
define TPROXY_USER=cat
define TPROXY_PORT=1234

define LAN_IPV4={
  172.16.64.0/18,
  192.168.0.0/16
}
define LAN_IPV6={
  fe80::/10
}

define BYPASS_IPV4={
  0.0.0.0/8,
  10.0.0.0/8,
  100.0.0.0/8,
  127.0.0.0/8,
  169.254.0.0/16,
  172.16.0.0/12,
  192.0.0.0/24,
  192.0.2.0/24,
  192.88.99.0/24,
  192.168.0.0/16,
  198.18.0.0/15,
  198.51.100.0/24,
  203.0.113.0/24,
  224.0.0.0/4,
  233.252.0.0/24,
  240.0.0.0/4,
  255.255.255.255/32
}
define BYPASS_IPV6={
  ::/128,
  ::1/128,
  ::ffff:0:0/96,
  100::/64,
  64:ff9b::/96,
  2001::/32,
  2001:10::/28,
  2001:20::/28,
  2001:db8::/32,
  2002::/16,
  fc00::/7,
  fe80::/10,
  ff00::/8,
  2409:8000::/20,
  2408:8000::/20,
  240e::/18
}

table inet cat_tproxy {
  chain cat_prerouting {
    type filter hook prerouting priority mangle; policy accept;

    meta l4proto { tcp, udp } socket transparent 1 mark set $TPROXY_MARK
    socket transparent 0 socket wildcard 0 return

    fib daddr type local return

    ip daddr $LAN_IPV4 meta l4proto { tcp, udp } th dport 53 tproxy ip to :$TPROXY_PORT meta mark set $TPROXY_MARK accept
    ip6 daddr $LAN_IPV6 meta l4proto { tcp, udp } th dport 53 tproxy ip6 to :$TPROXY_PORT meta mark set $TPROXY_MARK accept

    ip daddr $BYPASS_IPV4 return
    ip6 daddr $BYPASS_IPV6 return

    meta l4proto { tcp, udp } tproxy to :$TPROXY_PORT meta mark set $TPROXY_MARK accept
  }

  chain cat_output {
    type route hook output priority mangle; policy accept;

    meta skuid $TPROXY_USER return

    fib daddr type local return
    fib daddr type broadcast return

    ip daddr $LAN_IPV4 meta l4proto { tcp, udp } th dport 53 meta mark set $TPROXY_MARK
    ip6 daddr $LAN_IPV6 meta l4proto { tcp, udp } th dport 53 meta mark set $TPROXY_MARK

    ip daddr $BYPASS_IPV4 return
    ip6 daddr $BYPASS_IPV6 return

    meta l4proto { tcp, udp } meta mark set $TPROXY_MARK
  }
}
