MBTN_LEFT cycle pause
MBTN_LEFT_DBL cycle fullscreen
MBTN_MID ignore
MBTN_RIGHT script-binding select/menu

t script-binding stats/display-stats-toggle #menu: 查看 > 显示统计信息

################
## 着色器列表 ##
################
Ctrl+1 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A (Fast)"
Ctrl+2 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B (Fast)"
Ctrl+3 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C (Fast)"
Ctrl+4 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_Restore_CNN_S.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode A+A (Fast)"
Ctrl+5 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_Soft_S.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode B+B (Fast)"
Ctrl+6 no-osd change-list glsl-shaders set "~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Upscale_Denoise_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Restore_CNN_S.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"; show-text "Anime4K: Mode C+A (Fast)"
Ctrl+7 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F32.glsl"; show-text "ArtCNN: C4F32"
Ctrl+8 no-osd change-list glsl-shaders set "~~/shaders/ArtCNN_C4F32_DS.glsl"; show-text "ArtCNN: C4F32 DS"
Ctrl+0 no-osd change-list glsl-shaders set "~~/shaders/KrigBilateral.glsl:~~/shaders/nlmeans_temporal.glsl:~~/shaders/AiUpscale_HQ_Sharp_4x_Photo.glsl"; show-text "KnA"
Ctrl+` no-osd change-list glsl-shaders clr ""; show-text "GLSL shaders cleared"
Ctrl+Alt+s show-text "Active shaders: ${glsl-shaders}"

##############
## 滤镜列表 ##
##############
##⇘⇘很多滤镜不支持 无-copy 的纯硬解方式（即 hwdec=xxxx )，最好使用 hwdec=no 或 hwdec=xxxx-copy 获得更好的兼容性
##其它未列出的方案按需添加修改，滤镜的详细语法说明参见 https://hooke007.github.io/unofficial/mpv_filters.html

##VS的补帧类脚本只能同时启用单个，启用另一个前先关闭其它
b vf toggle vapoursynth="~~/vs/motioninterpolation.vpy"
n vf toggle vapoursynth="~~/vs/rife-ncnn.vpy"
Ctrl+~ vf clr ""; show-text "vapoursynth cleared" # 清空列表 —— 视频滤镜
Ctrl+Alt+v show-text "Active vapoursynth: ${vapoursynth}"

# ──────────────────────────────────────────────────────────────────────
# Scripts
# ──────────────────────────────────────────────────────────────────────
Alt+f script-binding selectformat/menu

Ctrl+f script-binding subtitle_lines/list_subtitles
Ctrl+F script-binding subtitle_lines/list_secondary_subtitles

g script-binding sponsorblock/set_segment
Ctrl+g script-binding sponsorblock/submit_segment
