#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
# 从下到上打印搜索结果。AUR 结果将首先打印。
BottomUp
# 假设所有目标都来自 AUR。此外，sysupgrade 等操作将仅作用于 AUR 包。
# AurOnly
# 在长时间构建期间定期在后台调用 sudo 以防止其超时。
SudoLoop
# 在 sysupgrade 期间也检查 AUR 开发包的更新。当前仅支持 Git 包。
Devel
# 安装后删除未跟踪的文件。
CleanAfter
# 搜索 AUR 包时查找匹配的提供者。当找到多个提供者时，将出现一个菜单提示您选择一个。这会增加依赖解析时间，尽管这应该不明显。
Provides = all
# 提示导入每个 PKGBUILD 的 \\fBvalidpgpkeys\\fR 字段中的未知 PGP 密钥。
PgpFetch
# 在 sysupgrade 期间，paru 将首先执行刷新，然后显示其组合的仓库和 AUR 包升级菜单。然后，在审查 PKGBUILDs 之后，仓库和 AUR 升级将开始，无需手动干预。
CombinedUpgrade
# 在 sysupgrade 期间打印新新闻。
# NewsOnUpgrade
# 使用 pacman 的 --ask 标志自动确认包冲突。Paru 提前列出冲突。paru 可能无法检测到冲突，导致包在未经用户确认的情况下被删除。
UseAsk
# 跳过审查过程。
# SkipReview
# 提交审查期间对 pkgbuilds 所做的更改。
SaveChanges
# 即使缓存中有副本，也始终构建目标包。如果设置为 all，则所有包都会被重建，而不仅仅是目标包。如果设置为 tree，则重建整个依赖树，包括已满足的依赖项。
Rebuild = all
# 安装包后移除 makedepends。如果设置为 ask，构建期间将出现一个菜单，允许那时选择一个选项。
RemoveMake
# 以类似于 pacman 的 VerbosePkgLists 选项的格式显示更新的详细列表。
UpgradeMenu
# 禁用当 AUR 包更新时，旧版本将从本地仓库中移除。
# KeepRepoCache


#LocalRepo
Chroot = /home/deck/Projects/paru/chroot
#Sign
#SignDb

# AurUrl = https://aur

#
# Binary OPTIONS
#
[bin]
# 启用 fm 审查模式，其中使用命令指定的文件管理器完成 PKGBUILD 审查。
FileManager = yazi
# 将参数传递给 makepkg。这些标志传递给 paru 调用 makepkg 的每个实例。在传递给 makepkg 之前，参数在空白字符上分割。
#MFlags = --skippgpcheck
# 将参数传递给 sudo。这些标志传递给 paru 调用 sudo 的每个实例。在传递给 sudo 之前，参数在空白字符上分割。
#Sudo = doas
