[general]
; 收割线程每5秒检查一次已退出的客户端、配置文件更改以及CPU/iGPU功耗平衡
reaper_freq=5

; GameMode 可以调整游戏进程的优先级。你可以在此处输入 0 到 20 之间的任意值，该值会被取反并作为 nice 值应用（0 表示不改变）。默认值为 0。
; 要使用此功能，用户必须被添加到 gamemode 组中（然后重启）：
; sudo usermod -aG gamemode $(whoami)
renice=0

[custom]
start=powerprofilesctl set performance
end=powerprofilesctl set balanced
