--ozone-platform=wayland
--enable-features=VaapiIgnoreDriverChecks,AcceleratedVideoEncoder,AcceleratedVideoDecodeLinuxGL

--no-sandbox

--ignore-gpu-blocklist
--disable-gpu-driver-bug-workaround
--enable-unsafe-webgpu

--enable-wayland-ime
--wayland-text-input-version=3
