name: Generate Rules

on:
    push:
        branches:
            - main
            - Proxy
    workflow_dispatch:
    schedule:
        - cron: '30 23 * * *'

permissions:
    contents: write

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Proxy branch
              uses: actions/checkout@v6
              with:
                  ref: Proxy
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Checkout scripts
              run: |
                  git fetch origin main
                  git checkout origin/main -- .github/scripts/rules.sh

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                  go-version: 'stable'
                  cache: false

            - name: Install dependencies
              run: |
                  mkdir -p .tmp

                  # cidr-merger
                  go install github.com/zhanhb/cidr-merger@latest

                  # mihomo
                  mihomo_version=$(curl -fsSL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
                  mihomo_url="https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-v3-go123-${mihomo_version}.gz"
                  curl -fsSL "$mihomo_url" -o .tmp/mihomo.gz
                  gunzip -c .tmp/mihomo.gz > .tmp/mihomo
                  chmod +x .tmp/mihomo
                  echo ".tmp" >> $GITHUB_PATH

            - name: Run scripts
              run: |
                  set -e
                  chmod +x .github/scripts/rules.sh
                  .github/scripts/rules.sh

            - name: Clean up
              run: |
                  rm -rf .tmp

            - name: Commit and push
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

                  git rm -rf .github

                  git add rules
                  git commit -m "chore: update rules $(date +'%Y-%m-%d')"
                  git push origin Proxy
